name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Build container image
        run: docker build -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/aquawise:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/aquawise:latest

      - name: Setup SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.DO_SSH }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH and Pull Docker Image
        run: |
          cat ~/.ssh/id_rsa
          ssh root@159.65.120.239 "doctl registry login --expiry-seconds 1200"
          ssh root@159.65.120.239 "docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/aquawise:latest"