name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: . # or the path to your Dockerfile
                  file: ./Dockerfile # adjust if your Dockerfile is in a different location
                  push: true
                  tags: ignaskav/aquawise-be:latest
            # - name: Install doctl
            #   uses: digitalocean/action-doctl@v2
            #   with:
            #       token: ${{ secrets.DO_TOKEN }}

            # - name: Build container image
            #   run: docker build -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/aquawise:be .

            # - name: Login to DO
            #   run: doctl registry login --expiry-seconds 1200

            # - name: Push image to DigitalOcean Container Registry
            #   run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/aquawise:be
